# ansible-galaxy install -r requirements.yml
# ansible-playbook playbook.yml -i inventory.ini -kK --ask-vault-pass


- hosts: all
  become: yes
 
  tasks:
    - name: install pip
      ansible.builtin.apt:
          name: python3-pip #=23.0.1+dfsg-1  # Action от hexlet не понимает эту версию... у меня дебиан Bookworm
          state: present
          update_cache: yes
      tags: 
      - prep

  roles:
    - role: geerlingguy.pip
      tags: 
      - prep



- hosts: dbservers
  become: yes
  tasks:
    - name: Remove container
      community.docker.docker_container:
        name: postgres-db
        state: absent
      tags: 
      - reinstall-db
      - reinstall-redmine        
      - del-db


    - name: Delete db

      ansible.builtin.file:
        state: absent
        path: /var/pgdata
      tags: 
      - del-db
      - reinstall-db
      - reinstall-redmine       


    - name: Creates container db
      community.docker.docker_container:
        name: postgres-db
        hostname: postgres-db
        image: "postgres:16"
        restart_policy: always
        state: started
        ports:
          - 5432:5432
        volumes:
          - /var/pgdata:/var/lib/postgresql/data
        env: # Настраиваем
 #         NODE_ENV: production
          POSTGRES_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
          POSTGRES_USER: "{{ REDMINE_DB_USERNAME }}"

      tags: 
      - install-redmine      
      - reinstall-db
      - install-db 
      - reinstall-redmine 

# 

    - name: Change dir pgdata permission
    
      ansible.builtin.file:
        path: /var/pgdata
        owner: root
        group: user
        mode: u+rw,g+rw,o-rw
        recurse: true
      tags: 
      - install-redmine       
      - reinstall-db
      - install-db  
      - reinstall-redmine 

    - name: Change dir pgdata permission
    
      ansible.builtin.file:
        path: /var/pgdata
        owner: user
        group: user
        mode: u+rwx,g+rwx,o+x
      tags: 
      - install-redmine       
      - reinstalldb
      - install-db       
      - reinstall-redmine 









# обновление файла pg_hba.conf по шаблону jinja

    - name: update pg_hba.conf
    
      ansible.builtin.template: 
        src: "pg_hba.conf.j2"
        dest: "/var/pgdata/pg_hba.conf"
      tags: 
      - install-redmine       
      - reinstall-db
      - install-db
      - reinstall-redmine 

    - name: Restart a container

      community.docker.docker_container:
        name: postgres-db
        restart: true  
        state: started
      tags: 
      - install-redmine       
      - reinstall-db
      - install-db        
      - reinstall-redmine 










- hosts: webservers
  become: yes




  tasks:


    - name: Remove container
      community.docker.docker_container:
        name: redmine
        state: absent
      tags: 
      - del-redmine  
      - reinstall-redmine        

    - name: Set env
      ansible.builtin.template: 
        src: "redmine.env.j2"
        dest: "/root/.env"
      tags: 
      - install-redmine       
      - reinstall-redmine 


    - name: Creates container redmine  
      community.docker.docker_container:
        name: redmine
        #recreate: true
        #restart: true        
        image: "redmine:5.1.3"
        restart_policy: always
        state: started
        ports:
          - "{{ REDMINE_HTTP_INNER_PORT }}:3000"
        etc_hosts:
          postgres-db: "{{ DB_POSTGRES }}"
        env_file: "/root/.env"

      tags:
      - reinstall-redmine       
      - install-redmine 

    - name: Restart container redmine  
      community.docker.docker_container:
        name: redmine
        #recreate: true
        restart: true        
        image: "redmine:5.1.3"
        restart_policy: always
        state: started
        ports:
          - "{{ REDMINE_HTTP_INNER_PORT }}:3000"
        etc_hosts:
          postgres-db: "{{ DB_POSTGRES }}"

        env_file: "/root/.env"
      tags:
      - restart-redmine       


    - name: Set HTTP check
      ansible.builtin.template: 
        src: "conf.yaml.j2"
        dest: "/etc/datadog-agent/conf.d/http_check.d/conf.yaml"
      notify:
        - restart datadog-agent       
      tags: 
      - restart-datadog
      - prep



  handlers:
    - name: restart datadog-agent
      ansible.builtin.service:
        name: datadog-agent
        state: restarted
      tags: 
      - restart-datadog 
      - prep



  roles:
    - role: DataDog.datadog
      tags: 
      - prep    





 

      